### ISSUE TITLE
`npm` warning  Unsupported engine

### ISSUE THREAD

**Issue by sourcevault** [tests-always-included/option-parser-js#2]
Is there something that we can do about the error ?

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'option-parser@1.0.0',
npm WARN EBADENGINE   required: { node: '>=0.6', npm: '~1' },
npm WARN EBADENGINE   current: { node: 'v15.12.0', npm: '7.19.1' }
npm WARN EBADENGINE }
```

**Comment by fidian** [comment]
Absolutely, I have addressed this in 3b057d3. Version 1.0.1 does not have this restriction any longer.

However, you might want to consider switching to docopt. It does a lot more in a far easier way.

**Comment by sourcevault** [comment]
https://github.com/stuartcarnie/docopt.coffee

**Comment by sourcevault** [comment]
I am sorry but :

https://github.com/stuartcarnie/docopt.coffee

seems a lot more complicated and error prone. 

I also need `-v` and `-vv` flags for `remotemon` (https://github.com/sourcevault/remotemon).

The documentation does not provide information on how to do it in `docopt`.
