### ISSUE TITLE
throwing errors uses "." concatenation instead of +

### ISSUE THREAD

**Issue by jhundley9109** [tests-always-included/option-parser-js#3]
Is there a bunch of Perl devs on this project?! "." concatenation is a better operator anyhow but it isn't correct for javascript!

The file option-parser.js has a couple throws that use the incorrect syntax for concatenation. The statements are as follows:

throw new Error('No parameter named ' . name); 
throw new Error('Value needed for -' . arg);

Just need to use them to use + instead so the error message can properly be caught higher up the chain. 

Should be a super duper simple fix.

Thanks for your work on this project!

**Comment by fidian** [comment]
Close, one perl dev was related to the code, but the real culprit was that this was ported from [option-parser-php](https://github.com/tests-always-included/option-parser-php).

Thanks for letting us know that there was a problem. I've published version 1.0.2.
